services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.windows
    command: uvicorn app:app --host 0.0.0.0 --port 9999
    ports:
      - "9999:9999" # Map port 8000
    volumes:
      - ./server:/app # Mount server code for live updates
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
